### ISSUE TITLE
[MStore Expo] - App Stay hang when payment is selected 

### ISSUE THREAD

**Issue by rmsoftengine** [inspireui/support#1327]
Hello Admin,
I am really stuck in the payment page. When I select the payment type and click next the page hang and I do not go any further. As per the demo the app should show me confirmation page with the order in processing state in woocommerce.
I am connecting woocommerce plugin for my app.
I have spent last 7 days but couldn't get any further. 
here is the page 
![image](https://user-images.githubusercontent.com/22434913/68091834-9de5e580-fe7c-11e9-868f-93e2ebed7920.png)

If you want I can give you the source code of the project. I badly need help with this.

my product name: mstore-expo.
Please tell me any info required from me, I would supply you immidiately.
Thanks

**Comment by rmsoftengine** [comment]
![image](https://user-images.githubusercontent.com/22434913/68094024-14421200-fe94-11e9-8369-0a9914f03bd1.png)

I have got these folder structure for the template..
and my purchase information is as below
![image](https://user-images.githubusercontent.com/22434913/68094040-418ec000-fe94-11e9-8328-8a669aace366.png)

**Comment by minhcasi** [comment]
@rmsoftengine  - could you help to take the whole screenshot with your user name so that we could verify on the system - sorry for inconvenience

**Comment by muhaiminulIslamIkhlas** [comment]
Login option also not working. It throws an error. But order save in woocommerc.  
Login it throws
![Screenshot_20191103-182438_Expo](https://user-images.githubusercontent.com/56554565/68098089-f5b83700-fee4-11e9-80d5-8cc78a421b8d.jpg)

**Comment by muhaiminulIslamIkhlas** [comment]
But it doesn't go further. Stucks in the payment page.

**Comment by muhaiminulIslamIkhlas** [comment]
@minhcasi

**Comment by rmsoftengine** [comment]
here is the full screenshot of the purchase
![image](https://user-images.githubusercontent.com/22434913/68098895-4ca71780-feb7-11e9-8fb6-aed9e1910dfb.png)
@minhcasi

**Comment by muhaiminulIslam** [comment]
@minhcasi I am using default checkout page of woocommerce. Can say what is the role of Mstore Api template.php. We need immediate help as we stuck here. 

In payment page we stuck and can't go further

**Comment by minhcasi** [comment]
@rmsoftengine - could you zip the current source and send to support@inspireui.com - also sharing your admin login so that we could help for checking the plugins config - thanks

**Comment by rmsoftengine** [comment]
I have emailed the details.

**Comment by rmsoftengine** [comment]
@concuacon  @minhcasi  I have not heard anything yet. Do you guys have any update on this?
Thanks

**Comment by concuacon** [comment]
Hello @rmsoftengine I have fixed and pushed the code for you, and I also edited your config in your WordPress admin page, please check and feedback for me.

**Comment by rmsoftengine** [comment]
Hello, @concuacon  I do not see any changes in my gitlab. There is no Merge request or any branch exists.. Have you actually pushed the code?
Could you please update me?
Thanks

**Comment by concuacon** [comment]
I just pushed it back, you can check it again

**Comment by rmsoftengine** [comment]
Hello, @concuacon  which location you have pushed? 
my code repo is here. https://gitlab.com/ardites/softengine-react-native
and again I do not see any changes. Have you committed in my repo? or somewhere else?

**Comment by concuacon** [comment]
Please check branch dev

**Comment by rmsoftengine** [comment]
Found that now.. Thanks a lot

**Comment by rmsoftengine** [comment]
still getting error.
after adding products whenever I am click on the CART then getting error.
![imgpsh_fullsize](https://user-images.githubusercontent.com/22434913/68378709-7759d000-0144-11ea-862e-5ed9532cac93.png)
its in IOS

**Comment by concuacon** [comment]
I just updated the code on your dev branch, you can review it,

**Comment by rmsoftengine** [comment]
Hello @concuacon , Thanks for the help. It works as expected now. However One thing is related to this is when the order is submitted and I am getting a thanks you message there is a woocommerce_thankyou hook I have added is not executing. DO you have any idea for that?

**Comment by rmsoftengine** [comment]
Do I need to put this action somewhere in the mstore-api-template.php?
as below?
 do_action('woocommerce_thankyou');
if so then where should I put my custom code for this?

**Comment by concuacon** [comment]
Hi, we're glad that it help, please give us some feedback/rating to this page https://codecanyon.net/downloads if the product is helpful for your business, we are working hard to update more awesome and powerful features on next coming version release. Let us know if you have any feedback. Thank you very much! :blush:
