### ISSUE TITLE
[FluxStore1.5.7] - Multiple Issues - Product with Attributes Showing Unavailable , Shipping Page Issue, Order Post Issue

### ISSUE THREAD

**Issue by siyashamsudeen** [inspireui/support#1359]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

A. Products with attributes are showing as Unavailable in the app . when attributes are removed then it is showing the add to cart button. 

<img width="250" alt="Screen Shot 2019-11-11 at 12 05 19 AM" src="https://user-images.githubusercontent.com/57159602/68549316-cccffe80-041c-11ea-9e44-954c19cf1781.png">

B. As i proceed with add to cart . when i click on the Select Address by location . it doesnt load. 
i created an api key ( Google Maps JS Api Key ) and added . But it is still not selecting location . 
Is it due to im trying from simulator ?

<img width="1147" alt="Screen Shot 2019-11-11 at 12 48 16 AM" src="https://user-images.githubusercontent.com/57159602/68549351-030d7e00-041d-11ea-87af-6b9b91bcceed.png">

<img width="263" alt="Screen Shot 2019-11-11 at 12 29 50 AM" src="https://user-images.githubusercontent.com/57159602/68549358-086ac880-041d-11ea-928c-0960ca8d2c96.png">

C. As i move further to shipping . it throws an exception error . my woocommerce site is set with normal shipping method - to customer billing address 

<img width="1093" alt="Screen Shot 2019-11-11 at 12 31 58 AM" src="https://user-images.githubusercontent.com/57159602/68549367-22a4a680-041d-11ea-9410-1ac631c2e2e4.png">
<img width="911" alt="Screen Shot 2019-11-11 at 12 32 07 AM" src="https://user-images.githubusercontent.com/57159602/68549369-26d0c400-041d-11ea-88a2-e97d871c2586.png">
<img width="278" alt="Screen Shot 2019-11-11 at 12 31 51 AM" src="https://user-images.githubusercontent.com/57159602/68549371-2a644b00-041d-11ea-8b46-5686715cb23b.png">

This error doesn't comes when i give the value isShipping: False

But then what is this shipping part for ?

C. As i remove shipping and go forward . im getting error when posting the order with COD Option. 
Currently i have enabled only COD Option . 

<img width="275" alt="Screen Shot 2019-11-11 at 12 33 12 AM" src="https://user-images.githubusercontent.com/57159602/68549397-6dbeb980-041d-11ea-9616-28c8bc1ec10b.png">

D. I installed the WPML to WP API - but my product name and description is not translated in app as how it is translated in the website. ( Arabic Translation )

Do i have to do any setting after installing the wpml - wp api plugin

For Eg see below:
<img width="260" alt="Screen Shot 2019-11-11 at 12 57 43 AM" src="https://user-images.githubusercontent.com/57159602/68549491-7bc10a00-041e-11ea-9e42-8be04bbf31c2.png">
<img width="1322" alt="Screen Shot 2019-11-11 at 12 58 23 AM" src="https://user-images.githubusercontent.com/57159602/68549492-7c59a080-041e-11ea-8685-2585649a91d9.png">

Doubts:

a.Does the app automatically fetch and shows the enabled payment options in WooCommerce ?
b. If i enable paypal and configure in woocommerce? do i have to again configure it in the app config.dart?

c. How do i enable multiple currency ? how do customers be able to switch their currency ?

d. i see that in the config.dart file i have to add all countries 

e. How does push notifications work ? is it possible to send from wordpress  / woocommerce admin dashboard ?

2. Screenshots

3. My screenshot of the purchase product or my comment:

Previously Added comment:

<img width="652" alt="Screen Shot 2019-11-11 at 1 01 51 AM" src="https://user-images.githubusercontent.com/57159602/68549530-e2debe80-041e-11ea-86a7-059166531230.png">

3. Config files (optional)

https://azmedia.a2hosted.com/temp-files/config.dart
https://azmedia.a2hosted.com/temp-files/config.json

Im also sending an email with admin account of woocommerce to previously contacted with Subject as the ticket number . 

truong@inspireui.com
minh@inpireui.com
support@inspireui.com

Please help to fix these issues and launch my app asap . i have been behind this one since a very long time now . i badly want to get all this sorted and get the app running .

**Comment by vumanhsn97** [comment]
Hi @siyashamsudeen 
We fixed your issues (A, C) on version 1.7.8. With issue B, please fill your api on folder ios and android. Make sure your api is correct. You can see more information at [](https://pub.dev/packages/place_picker). With issue D, you can replace locale = "ar" in lib/models/app.dart [](https://tppr.me/3UfL5)

If you want to fix it, you can do like this.
A: Replace file in lib/screen/detail/product_variant.dart to [](https://gofile.io/?c=lvEedk)
C: Replace file
- lib/models/order.dart to [](https://gofile.io/?c=n1y5Ir)
- lib/services/woo_commerce.dart to [](https://gofile.io/?c=IOJP1H)

**Comment by siyashamsudeen** [comment]
Hi, 

Thank you so much for your support. 

Well, i didn't understand the part of version 1.7.8 . Is there a new version released ? Im Currently using FluxStore1.5.7 

With issue D : you have asked to replace locale to “Ar” 

I dont want my default language to be Arabic . Only when user selects the arabic version it must show arabic . For this where i have to make the replacement . Or is it the same ? 

The others i will check as soon as im on a system And revert if its working . 

Well I still didnt get any reply to the doubts/concerns i have for the below 

Doubts:

1. Does the app automatically fetch and shows the enabled payment options in WooCommerce ?
2. If i enable paypal and configure in woocommerce? do i have to again configure it in the app config.dart?

3.  How do i enable multiple currency ? how do customers be able to switch their currency ?

4. i see that in the config.dart file i have to add all countries

5. How does push notifications work ? is it possible to send from wordpress / woocommerce admin dashboard ?

**Comment by siyashamsudeen** [comment]
I replaced the files with the ones you gave and now the app is nor launching . it is throwing error as below: 

i think the file is wrong or something . please check 

<img width="1196" alt="Screen Shot 2019-11-12 at 1 58 04 AM" src="https://user-images.githubusercontent.com/57159602/68619409-741e6580-04f1-11ea-8fb5-901ec9504aa1.png">

**Comment by siyashamsudeen** [comment]
for B: i added the correct api key enabling Google Places, Android & IOS Google Maps SDK in the api key. 

it now loads the places in the list but it is not showing on the marker . it shows blank . 

Please help to fix this as well . Kindly note that the above error issue after replacing the files are not resolved. 

<img width="258" alt="Screen Shot 2019-11-12 at 2 56 49 AM" src="https://user-images.githubusercontent.com/57159602/68622533-599bba80-04f8-11ea-937d-994c1b3c8c5d.png">
<img width="271" alt="Screen Shot 2019-11-12 at 2 57 01 AM" src="https://user-images.githubusercontent.com/57159602/68622534-599bba80-04f8-11ea-9d25-9c77d49e9b4b.png">

**Comment by siyashamsudeen** [comment]
Still waiting for the response. 

Thank You

**Comment by minhcasi** [comment]
@siyashamsudeen  try to test the map pick on the real device, on the simulator the map will not work.

Are you using the this order.dart file - https://www.dropbox.com/s/b49rgenwtpew20b/order.dart  - the above file is using for the Fluxstore Pro

**Comment by minhcasi** [comment]
@siyashamsudeen - pls try with latest version 1.5.8 and let us know if there is any issues - thanks
