### ISSUE TITLE
Language Switcher is not working in mstore mv 

### ISSUE THREAD

**Issue by inimist** [inspireui/support#1829]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: Language switcher not working, when I'm trying to switch from English to Arabic App reload but menu doesn't change to the Arabic language.

2. Screenshots issues:

When I selected English:-
![Screenshot_2020-01-14-16-12-52-91_f73b71075b1de7323614b647fe394240](https://user-images.githubusercontent.com/447618/72337610-e0336a80-36e8-11ea-8fd5-6cfc1033ebdc.png)

When I selected Arabic:-

![Screenshot_2020-01-14-16-11-03-66_f73b71075b1de7323614b647fe394240](https://user-images.githubusercontent.com/447618/72337696-ffca9300-36e8-11ea-9637-6e35bbe15b77.png)

3. Proof of my purchased:

![Screenshot at Jan 03 15-33-38](https://user-images.githubusercontent.com/447618/72337414-8c288600-36e8-11ea-8571-c598d97b8c72.png)

root\src\containers\Setting\LangSwitch.js

[import React from "react";
import {
  StyleSheet,
  Text,
  View,
  Picker,
  I18nManager,
  Alert,
} from "react-native";
import { Languages } from "@common";
import { Updates } from "expo";
import { connect } from "react-redux";

class LanguageSwitch extends React.Component {
  changeLocale = (locale) => {
    Alert.alert(Languages.Confirm, Languages.SwitchRtlConfirm, [
      {
        text: Languages.CANCEL,
        onPress: () => undefined,
      },
      {
        text: Languages.OK,
        onPress: () => {
          this.props.switchLanguage(locale);
          I18nManager.forceRTL(locale == "ar");
          Updates.reload();
        },
      },
    ]);
  };

  render() {
    const { lang } = this.props;
    return (
      <View style={styles.container}>
        <Picker
          style={styles.picker}
          selectedValue={lang}
          onValueChange={this.changeLocale}>
          <Picker.Item label={"🇰🇼 Arabic"} value={"ar"} />
          <Picker.Item label={"🇺🇸 English"} value={"en"} />
        </Picker>
        <View
          style={
            (I18nManager.isRTL && { flexDirection: "row-reverse" },
            styles.centered)
          }>
          <Text style={styles.plainBanner}>
            {Languages.currentLanguage + ": "}
          </Text>
          <Text style={styles.plainBanner}>
            {lang == "en" ? "English" : "Arabic"}
          </Text>
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  centered: {
    flexDirection: "row",
    marginBottom: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  picker: { backgroundColor: "#EEE", width: "50%" },
  container: {
    paddingVertical: 10,
    marginTop: 50,
    alignItems: "center",
    justifyContent: "center",
  },
  plainBanner: { fontSize: 14, marginTop: 15 },
});

const mapStateToProps = ({ language }) => {
  return {
    lang: language.lang,
  };
};

function mergeProps(stateProps, dispatchProps, ownProps) {
  const { dispatch } = dispatchProps;
  const { actions } = require("@redux/LangRedux");
  return {
    ...ownProps,
    ...stateProps,
    switchLanguage: (language) => actions.switchLanguage(dispatch, language),
  };
}
export default connect(
  mapStateToProps,
  null,
  mergeProps
)(LanguageSwitch);
](url)

**Comment by minhcasi** [comment]
@luyx2412 - pls help for investigating - thank you!

**Comment by inimist** [comment]
Hey @luyx2412  is there any update?

**Comment by luyx2412** [comment]
Hi @inimist 
Fixed this issue in next release version.

Thanks

**Comment by inimist** [comment]
Hey @luyx2412  can you please provide patches I can implement on my current code?

**Comment by luyx2412** [comment]
Hi @inimist 
- In `src/Router.js` line 33 with `ComponentDidmount` replace it with
`
  async componentDidMount() {
    NetInfo.fetch().then((state) => {
      this.props.updateConnectionStatus(state.type != "none");
      this.setState({ loading: false });
    });

    const { lang } = this.props;

    const currentLanguage = lang && lang.lang ? lang.lang : "en";

    await Languages.setLocale(currentLanguage);
  }
`
P/S: Fixed with next version, and feel free reopen the issue.

Thanks

**Comment by inimist** [comment]
![Screenshot_2020-01-18-14-04-38-74_f73b71075b1de7323614b647fe394240](https://user-images.githubusercontent.com/447618/72661010-92c24080-39fb-11ea-996c-c5229681d87f.png)

Hey @luyx2412  Thanks, But Still getting the issue this is just changing the menu align LTR. This didn't change the menu from English to Arabic.

After updating the `componentDidMount()` 

```
async componentDidMount() {
    await Languages.setLocale(this.props.lang);
    const { locale } = await Localization.getLocalizationAsync();
    console.warn(locale);
  }
```
**to**
```
async componentDidMount() {
    NetInfo.fetch().then((state) => {
      this.props.updateConnectionStatus(state.type != "none");
      this.setState({ loading: false }); 
    }); 
    const { lang } = this.props; const currentLanguage = lang && lang.lang ? lang.lang : "en";
    await Languages.setLocale(currentLanguage); 
  }
```
Can you please help me with this. If you or anyone from team could talk to me over skype I think this can be sorted in a matter of a few minutes for sure.

**Comment by minhcasi** [comment]
Hi Mohit, we got a lot of your spam questions on our email/ticket regarding the customization, pls try your best google before asking the question.

Also, contact your Client mj_brainstack request us for further supporting - thank you for your understanding
