### ISSUE TITLE
[FLUXSTORE MV] - Category can't show the Picture, Just Loading

### ISSUE THREAD

**Issue by antixirus** [inspireui/support#2691]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
![gambar](https://user-images.githubusercontent.com/57300649/79096636-ec7ea080-7d87-11ea-928d-c037243186c1.png)
![gambar](https://user-images.githubusercontent.com/57300649/79096653-f3a5ae80-7d87-11ea-8731-4c2e3ea5cf39.png)

2. Screenshots issues (required):
Forget the update 1.6.6 Fluxstore MV there are errors / bugs, here is an example, I did not make any changes, but the category does not display images, only loads
3. Proof of my purchased (required):
![gambar](https://user-images.githubusercontent.com/57300649/79096772-39627700-7d88-11ea-9a18-a339c8ccaa9d.png)

3. Config files (required)

**Comment by abedfatafta** [comment]
same is here , ticket opened before 2 days !

**Comment by minhcasi** [comment]
@antixirus - please help to download the latest 1.6.6b - we have fixed some build issues on this release - thank you!

**Comment by antixirus** [comment]
@minhcasi Hello sir, I have downloaded version 1.6.6b, but now I can't even log in to the application after changing the App Bundle ID from com.inspireui.fluxstore.vendor to com.sougroup.sangkek is just stuck loading. Can you help me sir?

Picture
![gambar](https://user-images.githubusercontent.com/57300649/79418163-1a5d2280-7fde-11ea-985d-231e057bc5ad.png)

**Comment by antixirus** [comment]
@minhcasi 
![gambar](https://user-images.githubusercontent.com/57300649/79419157-7628ab00-7fe0-11ea-9693-e732ad141f5b.png)

**Comment by minhcasi** [comment]
@antixirus  could i know if you have changed the path of folder - com/sougroup/sangkek

Also, please make sure to update the google file service if you are using login via SMS or Google

**Comment by antixirus** [comment]
@minhcasi I have changed the folder com/inspireui/fluxstore/vendor to
com/sougroup/sangkek/vendor and have also updated Google service.json but still cannot log in, please help

**Comment by antixirus** [comment]
This is a picture from Fluxstore 1.6.6b. I didn't change anything other than the Application Bundle ID, Secret Key and Customer Key, can't log in, just stop there.

![gambar](https://user-images.githubusercontent.com/57300649/79528930-82bb0b00-8095-11ea-8859-9dae48a690b9.png)

**Comment by antixirus** [comment]
@minhcasi @kvt0012 @minhtruong315 Please help me

**Comment by minhcasi** [comment]
@minhtruong315 - please help for checking

**Comment by minhtruong315** [comment]
@antixirus can u send me config files via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/2691

**Comment by antixirus** [comment]
@minhtruong315 Why is everything always about config sir? Even though it is Fluxstore version 1.6.6b, I have not changed any configuration other than comsume key, secret key and App Bundle ID. I did not change anything other than the things I mentioned above

**Comment by minhtruong315** [comment]
I dont know your website url, Secret Key and Customer Key. so I can't check login issue. because login is working well on our website.

**Comment by antixirus** [comment]
@minhtruong315 Done, i am send you full source

**Comment by abedfatafta** [comment]
How can i read available  countries , states , city from backend ? 

our wordpress customized per vendor , so it return available shipping location per  order based on customer from which vendors have bought 

in addition i want to cancel some check out filds - like zip code

**Comment by minhtruong315** [comment]
[tools.dart.zip](https://github.com/inspireui/support/files/4500793/tools.dart.zip)
replace common/tools.dart to fix image category

**Comment by minhtruong315** [comment]
<img width="1598" alt="Screen Shot 2020-04-20 at 9 10 26 AM" src="https://user-images.githubusercontent.com/10402500/79707502-e7b96f80-82e6-11ea-8f83-9cd6e745aad9.png">
you changed package id, but you don't download google-services.json again

**Comment by minhtruong315** [comment]
https://www.youtube.com/watch?v=C_9mk_MmvOQ&feature=emb_title
please follow this guide to config firebase

**Comment by antixirus** [comment]
@minhcasi 
![12](https://user-images.githubusercontent.com/57300649/79729642-eeada580-8319-11ea-9ace-d1ad43264d7c.png)

I get the error sir

**Comment by minhtruong315** [comment]
https://firebase.google.com/docs/cli#install-cli-windows
follow by this guide
