### ISSUE TITLE
[fluxstore] getting "Mstore checkout" every where in my website

### ISSUE THREAD

**Issue by ilyesrd** [inspireui/support#3119]
please i'm getting this error since i add mstore plugin to my website... please help!

<img width="1433" alt="Capture d’écran 2020-04-28 à 9 19 29 AM" src="https://user-images.githubusercontent.com/25514080/81483247-95f46d00-9234-11ea-9eb0-689842b171c3.png">

<img width="1433" alt="Capture d’écran 2020-05-09 à 8 40 55 PM" src="https://user-images.githubusercontent.com/25514080/81483338-68f48a00-9235-11ea-8bd4-8659768707c7.png">

**Comment by minhcasi** [comment]
@ilyesrd 

Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by ilyesrd** [comment]
@minhcasi 

it's done... could you please check this issues

**Comment by minhcasi** [comment]
@minhtruong315 - pls help to investigate

**Comment by minhtruong315** [comment]
@ilyesrd can u send  me admin account to login to your website via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/3119

**Comment by ilyesrd** [comment]
@minhtruong315 - I sent you the email

**Comment by ilyesrd** [comment]
@minhtruong315 did you find anything

**Comment by ilyesrd** [comment]
i want to add this too... so filters are not working at all in the app !! is it because of above problem?

![Screenshot_20200512-044114](https://user-images.githubusercontent.com/25514080/81637551-8f215200-940e-11ea-93c2-06c30d3f547d.png)
![Screenshot_20200512-044202](https://user-images.githubusercontent.com/25514080/81637555-934d6f80-940e-11ea-8a9a-4bca8a7eaebd.png)

**Comment by minhtruong315** [comment]
@ilyesrd I fixed duplicate MStore Checkout page. please check  again

**Comment by ilyesrd** [comment]
@minhtruong315 
i'm getting this error instead 

<img width="1438" alt="Capture d’écran 2020-05-14 à 4 25 25 AM" src="https://user-images.githubusercontent.com/25514080/81889326-27e4d880-959b-11ea-8316-d78ef7d741a4.png">

**Comment by minhtruong315** [comment]
@ilyesrd can u update MStore Api plugin to the latest version then check again. Thanks

**Comment by ilyesrd** [comment]
@minhtruong315 @minhcasi 
thanks, the first problem is solved ... what about the second one ?

**Comment by minhtruong315** [comment]
can u record screen for this  issue? I can't find the case to reproduce this issue.
Thanks

**Comment by ilyesrd** [comment]
@minhtruong315 
here is the record screen:
[SVID_20200515_112644.mp4.zip](https://github.com/inspireui/support/files/4633846/SVID_20200515_112644.mp4.zip)

**Comment by minhtruong315** [comment]
Hi @ilyesrd You need to enter price for products. it's empty so you can filter by price.

**Comment by ilyesrd** [comment]
@minhtruong315 
but filter by attribute still always not working!

**Comment by minhtruong315** [comment]
@ilyesrd I dont see this issue ```flutter: {categorys: [], pa_المقاس: [Instance of 'SubAttribute']}``` on my source code
Can u upload your source code to github then invite me: minhtruong315@gmail.com
I'll help you check it.
Thanks

**Comment by ilyesrd** [comment]
@minhtruong315 
please check the repo

**Comment by minhtruong315** [comment]
@ilyesrd I checked your source code. it's old version. I released version 1.7.3 on May 7. You need to download and check on the latest version. You also need to upgrade flutter 1.17

**Comment by ilyesrd** [comment]
@minhtruong315 
please add me to the gitlab repo: @rdah

**Comment by minhtruong315** [comment]
you can download source code on https://codecanyon.net/downloads

**Comment by minhcasi** [comment]
@ilyesrd - we have added your Gitlab account as well, please update the latest release `1.7.4` and mstore-api to fix this issue

Let us know if you have any further issue - very best

**Comment by ilyesrd** [comment]
@minhcasi 
I updated the project to the latest version as well as Flutter ... but the problem still there! ... I noticed that when I try to filter with an English attribute, it works well, but when I use the Arabic attribute, it doesn't work ... my application will use Arabic every where, I don't need english and i'll not use it... so that's why i did not install multilanguage plugin.. is it required to fix the problem?
<img width="512" alt="Capture d’écran 2020-05-23 à 11 55 23 AM" src="https://user-images.githubusercontent.com/25514080/82729155-36df2f80-9ced-11ea-8f9c-03a029ee10ac.png">
