### ISSUE TITLE
[FluxStore Pro] Problem with product variants

### ISSUE THREAD

**Issue by David9192** [inspireui/support#3367]
Step 1 (require): detail issues and screenshots

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by David9192** [comment]
When you select the product variants send this error message that appears in the photo. Sometimes it comes out when you play different variant several times or comes out playing only one. Also when a product is opened it says loading and it takes a long time to open. I need a solution

**Comment by David9192** [comment]
![82251449-d62dac80-9912-11ea-95c6-9d1a46274a78](https://user-images.githubusercontent.com/39241693/82716072-baecd500-9c63-11ea-9730-b6b1eb586855.png)

**Comment by David9192** [comment]
![97489000_248547929554739_1648465704413822976_n](https://user-images.githubusercontent.com/39241693/82716196-3a7aa400-9c64-11ea-9dee-d733c9f69def.jpg)
![97994878_577176002930340_7372724560912711680_n](https://user-images.githubusercontent.com/39241693/82716197-3b133a80-9c64-11ea-9c94-f3fd05f71d1f.jpg)

**Comment by minhcasi** [comment]
@David9192 - could you confirm you are using the latest `1.7.4`? as this issue is already fixed on latest release - thank you!

**Comment by David9192** [comment]
If I am using the latest version I have just updated and it has given me enough problems but this problem in particular of the variants I can not ignore a greeting thanks

**Comment by minhcasi** [comment]
Hi @David9192 - sorry i’m not sure to understand your point

You could try to override the detail screens source code from latest version into your current source. 

Order solution is init your source with the Git, and override the new source to check the code update. 

Let us know your checking - thank you!

**Comment by David9192** [comment]
Hi, I'm not a programmer, I'm just trying to get a solution for variable products that have an error, as in the photo I sent you.  I need a solution that I can implement with my little knowledge of flutter.  I have the latest version and it still doesn't work.  Thank you

**Comment by minhcasi** [comment]
This is could be a bug - Would you mind to download the attached file, rename to `product_variant.dart` file and override to `lib/screens/detail/` - let us know your checking

[product_variant.dart.txt](https://github.com/inspireui/support/files/4674966/product_variant.dart.txt)

**Comment by David9192** [comment]
ok I try and notify you thanks

**Comment by minhcasi** [comment]
@David9192 - pls confirm if the error is resolved :)

**Comment by David9192** [comment]
if the problem is fixed.  I only have another problem since the free shipping method recognizes a minimum order but does not recognize one when there is a coupon and it must be activated or hidden.  It should work since it comes integrated in woocomerce bolt does not work.

**Comment by philipvu30** [comment]
Hi @David9192 ,

I quite don't get what you mean. Would you mind providing a clearer explanation or detailed images?

**Comment by David9192** [comment]
When selecting a free shipping with the rule that it is activated only if there is a valid coupon.  This rule is not respected and the shipping is shown if there is a quota or not in the purchase, the shipping is always shown, although it shows if a valid coupon has been entered.  That's my problem.  Thank you

**Comment by David9192** [comment]
![58A46A1E-2542-4DA8-B5AB-416802301374](https://user-images.githubusercontent.com/39241693/83134688-b20c6100-a0b2-11ea-9860-8e343ee98296.png)

**Comment by philipvu30** [comment]
Do you mean this option right?

![image](https://user-images.githubusercontent.com/54442328/83219431-8369b580-a19a-11ea-83be-11667b1611ce.png)

**Comment by David9192** [comment]
Yes, of course I have this option indicated in the coupon but the shipping method does not recognize it in the application and shows the free shipping although there is no coupon placed

**Comment by philipvu30** [comment]
I see what you meant. 

FYI, this option has not been implemented in our code yet. I'll forward this feature request to our technical team. It might be added in the next release.

**Comment by David9192** [comment]
Ok
