### ISSUE TITLE
Multiple issues in Magento2

### ISSUE THREAD

**Issue by subhquad** [inspireui/support#3573]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues:
 1. Blank Screen when you click on reset password .
2.  In checkout page select address is not showing saved addresses in magento.
3. Banner image not loading loading from asset folder.Its working fine when we are providing external image link.
4. category images not pulling from magento2 . 
5. Payment integration webview not working 
6. Product having variants showing as zero price and variants not displaying

+ Product & version: Fluxstore Pro  1.7.5
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: iPhone 11
+ Screenshot issues (drag the file to attach here): 
<img width="361" alt="Screenshot 2020-06-02 at 13 40 50" src="https://user-images.githubusercontent.com/10830054/83645461-6d992d80-a5aa-11ea-9079-b3acf5614fea.png">
<img width="336" alt="Screenshot 2020-06-02 at 13 46 14" src="https://user-images.githubusercontent.com/10830054/83645476-725de180-a5aa-11ea-8c59-e13f0dd909c1.png">
<img width="352" alt="Screenshot 2020-06-02 at 13 50 36" src="https://user-images.githubusercontent.com/10830054/83645496-7853c280-a5aa-11ea-92a3-f6d1ab1b646b.png">
<img width="343" alt="Screenshot 2020-06-02 at 13 18 38" src="https://user-images.githubusercontent.com/10830054/83645508-7be74980-a5aa-11ea-8617-dbd26dbe6e0b.png">

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

80f2ca3f-3e8f-43cd-97ba-9dd311d5fb75

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by subhquad** [comment]
Requested for gitlab access.

**Comment by minhtruong315** [comment]
Hi @subhquad can u upload your source code to git repo then invite me: minhtruong315@gmail.com
I will help you check and fix on your source code
Thanks

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!

**Comment by subhquad** [comment]
Provided access

**Comment by minhtruong315** [comment]
hi @subhquad Please download Fluxstore version 1.7.5 then try again with your issues. if you have any issues, please tell me.
Thanks

**Comment by subhquad** [comment]
We are using 1.7.5 . For reset password we are using config to redirect to forgot password weblink . All other issues are not fixed yet.
Provided access to git .checkout develop branch.
https://github.com/subhquad/magento-flutter

**Comment by minhtruong315** [comment]
Hi @subhquad all issues happen on our website?
<img width="878" alt="Screen Shot 2020-06-09 at 7 12 02 AM" src="https://user-images.githubusercontent.com/10402500/84092096-a01aae80-aa20-11ea-9e34-f29acf7400a7.png">

**Comment by subhquad** [comment]
Please checkout develop branch
https://github.com/subhquad/magento-flutter/blob/develop/source/lib/common/config.dart

**Comment by subhquad** [comment]
Payment error
enabled
  /// Enable Payment option
  "EnableOnePageCheckout": true,
  "NativeOnePageCheckout": true,



<img width="342" alt="Screenshot 2020-06-09 at 13 56 58" src="https://user-images.githubusercontent.com/10830054/84150128-5601ef00-aa59-11ea-86d8-8f805b189aaf.png">

**Comment by minhtruong315** [comment]
Hi @subhquad one page checkout only supports on woo commerce, it doesn't support for magento.
I fix some issues. pls pull the source code and check again.
- Fixed reset password
- Magento version doesn't support save and show address in backend
- Banner image only loads url for now.  if you want to load assets, you must edit code.
- Fixed categories image
- Payment webview doesn't work on magento now.
- Take me screenshot for product variant
Thanks

**Comment by subhquad** [comment]
Please find screenshot for variant product . 
Tilda Basmati which is under category grocery.

<img width="366" alt="Screenshot 2020-06-10 at 09 19 14" src="https://user-images.githubusercontent.com/10830054/84244745-fc063580-aafb-11ea-9440-a78566e1b9f8.png">
<img width="353" alt="Screenshot 2020-06-10 at 09 18 58" src="https://user-images.githubusercontent.com/10830054/84244757-00cae980-aafc-11ea-9e06-dab84e840eb4.png">

**Comment by minhtruong315** [comment]
Hi @subhquad I can't see any products on your website
<img width="1643" alt="Screen Shot 2020-06-11 at 5 32 06 PM" src="https://user-images.githubusercontent.com/10402500/84375293-8ab4a880-ac09-11ea-9a68-0d452773c3b9.png">

**Comment by subhquad** [comment]
> Hi @subhquad I can't see any products on your website
> <img alt="Screen Shot 2020-06-11 at 5 32 06 PM" width="1643" src="https://user-images.githubusercontent.com/10402500/84375293-8ab4a880-ac09-11ea-9a68-0d452773c3b9.png">

Can you check now

**Comment by minhtruong315** [comment]
Hi @subhquad I fixed on your source code. please pull the source code and check again.
![Simulator Screen Shot - iPhone 11 - 2020-06-11 at 21 19 39](https://user-images.githubusercontent.com/10402500/84397771-46d19b80-ac29-11ea-96a3-18bb152e227b.png)

**Comment by subhquad** [comment]
The details page is working but still in category page the price is showing as 0

<img width="372" alt="Screenshot 2020-06-11 at 15 43 18" src="https://user-images.githubusercontent.com/10830054/84400870-7f0db580-abfa-11ea-996c-de96ea07ec41.png">

**Comment by minhtruong315** [comment]
@subhquad The magento api doesn't response the price for product configurable. so it  doesn't show price on products page. I will research and upgrade it later.
Thanks

**Comment by subhquad** [comment]
What’s the solution for it . How can you close the ticket when the issue is not fixed . Also regarding implementation of webview for payment gateway which is not supported by Fluxstore. What’s the solution . We can’t go live without these fixes .

**Comment by minhtruong315** [comment]
Hi @subhquad We will research and update in the future. it's hard functions.  We dont have any solution now.

**Comment by subhquad** [comment]
Which are the  payment gateway  it supports for Magento now ?  Please give us the list . Also are you working on the webview for the Magento ?
