### ISSUE TITLE
Variation price in 0

### ISSUE THREAD

**Issue by juancamilocanal** [inspireui/support#3598]
I have an issue with some variation products, the app shows them in 0 but in the cart and checkout they are fine. It does not happen with all products, and both on the woocommerce admin nad on the DB setting are the same to those products that do work correctly. 

Check out this video for the problem:
https://youtu.be/631OPXt-_EY

Check out a video of a product working fine:
https://youtu.be/bdFHelRDVRY

Proof of purchase:
![image](https://user-images.githubusercontent.com/818225/83689354-83abeb80-a5b4-11ea-931a-c25416ec0adc.png)

**Comment by minhcasi** [comment]
@juancamilocanal - We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can to get to your request as soon as possible.

Could you help to confirm this issue is happening on latest `1.7.5`? The team confirm it is fixed on latest release

**Comment by juancamilocanal** [comment]
I will test this and get back to you on this ticket.

**Comment by juancamilocanal** [comment]
I finnaly upgraded to the latest code. I'm sorry to say the issue still persists. Please help

**Comment by juancamilocanal** [comment]
I finally upgraded to the latest code. I'm sorry to say the issue still persists. Please help

**Comment by juancamilocanal** [comment]
I finally upgraded to the latest code. I'm sorry to say the issue still persists. Please help @minhcasi
