### ISSUE TITLE
magento issues

### ISSUE THREAD

**Issue by amjadalfawal** [inspireui/support#3705]
**_Step 1 (require): describe detail issues & screenshots_**
![image](https://user-images.githubusercontent.com/37481122/84523176-8e672e80-ace0-11ea-97f1-819bec1ea95e.png)

+ Detail Issues: 
update profile not working cant change the profile picture and sending the request show errors
I am using localhost for now I cant provide server url

+ Product & version:
+ Flutter (or React Native) version: 
flutter
+ Testing Device/Simulator: 
simulator

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

##########################################################################

**issue 1:**
**price not showing from outside**
![2020-06-15_17h28_11](https://user-images.githubusercontent.com/37481122/84669589-ae3f6200-af2d-11ea-9639-5fa2e1ff1c1f.png)
![image](https://user-images.githubusercontent.com/37481122/84703225-93d2ac00-af60-11ea-8f44-46e41bdc5a9f.png)

**issue2: the items take more than 5 seconds to load them to slow**  

**issue 3 :** 
**color not showing always** 
![image](https://user-images.githubusercontent.com/37481122/84669786-f2326700-af2d-11ea-9896-853f0643f6a5.png)
**issue 4:**
**when login or signup from the splash screen the whole app go wrong** 
![102587223_1625743737599649_1690108943079793939_n](https://user-images.githubusercontent.com/37481122/84670617-05920200-af2f-11ea-9c77-a0090db64199.png)
![104433802_1177370859272898_6525068156658358004_n (1)](https://user-images.githubusercontent.com/37481122/84670631-0aef4c80-af2f-11ea-8926-ce7f974e1f2c.png)
![103180001_705168200046514_1579871171368801818_n](https://user-images.githubusercontent.com/37481122/84670652-0fb40080-af2f-11ea-9716-ca9d5afc8fba.png)
![102340275_701673890621465_6963665674347746163_n](https://user-images.githubusercontent.com/37481122/84670663-12aef100-af2f-11ea-87e5-9b5492cb662a.png)

**issue 5:** 
**disable shipment give this error** 
**ps: I want to remove the shipping and address I tried to make them virtual products not work ethier**

![image](https://user-images.githubusercontent.com/37481122/84689227-54e52c00-af49-11ea-8ea3-0c1d7f39acbf.png)

**issue6 !important** : 
**Cart it's not synced on the website and app empty the cart from the app not deleting on website**

![83013257_608029293164051_2759378328702667844_n](https://user-images.githubusercontent.com/37481122/84826562-ca292d80-b02b-11ea-843a-daf014a3e981.png)

![image](https://user-images.githubusercontent.com/37481122/84825906-d5c82480-b02a-11ea-80b7-6fa3028c4fd5.png)

+ Product & version:
 1.7.5
+ Flutter (or React Native) version: 
flutter
+ Testing Device/Simulator: 
device

**Comment by amjadalfawal** [comment]
2 day waiting guys i send form

**Comment by minhcasi** [comment]
@amjadalfawal - could you try to share the host as public so that we could help with checking - it is not possible to connect your localhost `http://192.168.1.36/magento` - thanks

@minhtruong315 - pls confirm if the Edit profile is working on latest Magento

**Comment by amjadalfawal** [comment]
http://ecommerce.ejaferp.com/

**Comment by minhtruong315** [comment]
Hi @amjadalfawal Fluxstore supports to update email and change password on profile now.
You can replace these files to check changing email and password.
[lib.zip](https://github.com/inspireui/support/files/4784593/lib.zip)
We will research and update Fluxstore to change other user info.
Thanks

**Comment by amjadalfawal** [comment]
@minhtruong315  Thanks for answering  
@minhcasi I moved my other issues to this  issue as you asked me

**Comment by amjadalfawal** [comment]
@minhtruong315 when i replaced the files in lib.zip its give errors
![image](https://user-images.githubusercontent.com/37481122/84779067-95e24c80-afec-11ea-9c53-586fb37ee671.png)
![image](https://user-images.githubusercontent.com/37481122/84779089-9f6bb480-afec-11ea-811f-d8cb62ff0b41.png)

**Comment by minhtruong315** [comment]
@amjadalfawal replace models/product/product_variantion.dart
[product_variation.dart.zip](https://github.com/inspireui/support/files/4789590/product_variation.dart.zip)

**Comment by amjadalfawal** [comment]
what about the other issues

**Comment by minhtruong315** [comment]
@amjadalfawal 
issue 1: price not showing from outside. 
Magento Api doesn't support to response price for configurable product. So it will show zero price for configurable products. We will investigate and upgrade it in the future.

issue2: the items take more than 5 seconds to load them to slow
it depend on your hosting and the network.

issue 3, 4: can u upload your source code to github then invite me: minhtruong315@gmail.com

issue 5: disable shipment give this error
Magento checkout need shipping method to checkout, so you can't  disable address or shipping.

issue 6. Fluxstore doesn't support to sync cart in website.

**Comment by amjadalfawal** [comment]
issue 1: price not showing from outside.
Magento Api doesn't support to response price for configurable product. So it will show zero price for configurable products. We will investigate and upgrade it in the future. 
i fixed this issue by editing the API 

    public function getList(\Magento\Framework\Api\SearchCriteriaInterface $searchCriteria)
    {
        /** @var \Magento\Catalog\Model\ResourceModel\Product\Collection $collection */
        $collection = $this->collectionFactory->create();
        $this->extensionAttributesJoinProcessor->process($collection);

        $collection->addAttributeToSelect('*');
        $collection->joinAttribute('status', 'catalog_product/status', 'entity_id', null, 'inner');
        $collection->joinAttribute('visibility', 'catalog_product/visibility', 'entity_id', null, 'inner');
	$collection->addFinalPrice();

        $this->collectionProcessor->process($searchCriteria, $collection);

        $collection->load();

        $collection->addCategoryIds();
        $this->addExtensionAttributes($collection);
        $searchResult = $this->searchResultsFactory->create();
        $searchResult->setSearchCriteria($searchCriteria);
        $searchResult->setItems($collection->getItems());
        $searchResult->setTotalCount($collection->getSize());

        foreach ($collection->getItems() as $product) {
            $this->cacheProduct(
                $this->getCacheKey(
                    [
                        false,
                        $product->getStoreId()
                    ]
                ),
                $product
            );
        }

        return $searchResult;
    }

**Comment by amjadalfawal** [comment]
issue 1: price not showing from outside.
Magento API doesn't support to response price for configurable products. So it will show zero price for configurable products. We will investigate and upgrade it in the future.
I fixed this issue by editing the API

**Comment by minhtruong315** [comment]
Hi @amjadalfawal can you show me what you fixed?
Thanks

**Comment by amjadalfawal** [comment]
issue 5: disable shipment give this error
I made a workaround by making the address static and shipment method static inserted and disable the UI for them

**Comment by amjadalfawal** [comment]
**New issue found when adding item to cart  its add on Magento web cart and when remove the item from cart it's still saved on the web cart but it disappears from the app adding new items and placing order its order the web cart  + the app local cart need to sync both cart**

**Comment by minhtruong315** [comment]
> issue 1: price not showing from outside.
> Magento API doesn't support to response price for configurable products. So it will show zero price for configurable products. We will investigate and upgrade it in the future.
> **I fixed this issue by editing the API**

show me that you fixed so that I update it  on Fluxstore. Thanks

**Comment by minhtruong315** [comment]
> **New issue found when adding item to cart its add on Magento web cart and when remove the item from cart it's still saved on the web cart but it disappears from the app adding new items and placing order its order the web cart + the app local cart need to sync both cart**

Fluxstore doesn't support sync cart from website to app now

**Comment by amjadalfawal** [comment]
@minhtruong315 
I will share the fix tomorrow 
Fluxstore doesn't support sync cart from website to app now
there is a logical issue if there are items on you cart web and you place an order from the app it will place an order for all the items not what the end-user see  for example adding item from mobile and build cart model  that will add the item to web cart if the user goes back and remove the item and adding another item and build the cart model user will see one item on the local cart but placing order will place the both item

**Comment by minhtruong315** [comment]
@amjadalfawal Thanks for your report. I will investigate this issue and will update it in the future.

**Comment by minhcasi** [comment]
@amjadalfawal - the ability to sync cart from website to app is not available from the current Fluxstore version, we will consider upgrading it later due to high complexity of the feature.

**Comment by amjadalfawal** [comment]
issue6: SMS login Magento not retrieving the user order Magento #solved 
issue7: when user close the app and open it again it requires him to log in again user not cached  
new feature reviews Magento and rating not working  request

**Comment by amjadalfawal** [comment]
Fixed the cart issue

**Comment by amjadalfawal** [comment]
I will share my edits  @minhtruong315  sorry for being late 
#cart issue in lib\services  Future<bool> addToCart  + Future<bool> addItemsToCart replace them with tow functions below the problem is product id its not equal to item_id in the cart so the delete process not completed

`  Future<bool> addToCart(CartModel cartModel, String token, quoteId,
      {isDelete = false, guestCartId , List<dynamic> cartItems}) async {
    try {
      //amjad cart problem item_id its not equal to product id 
      List<dynamic> items;
      items = cartItems;
      //delete items in cart
      if (isDelete) {
        await Future.forEach(items, (key) async {
        //amjad cart problem items_id
        String productId = key['item_id'].toString();
         await http.delete(
              MagentoHelper.buildUrl(domain, "carts/mine/items/$productId"),
              headers: {'Authorization': 'Bearer $token'});
        });
         

        await http.delete(MagentoHelper.buildUrl(domain, "carts/mine/coupons"),
            headers: {'Authorization': 'Bearer $token'});
      }
      //add items to cart
      await Future.forEach(cartModel.productsInCart.keys, (key) async {
        Map<String, dynamic> params = Map<String, dynamic>();
        params["qty"] = cartModel.productsInCart[key];
        params["quote_id"] = quoteId;
        params["sku"] = cartModel.productSkuInCart[key];
        final res = await http.post(
            guestCartId == null
                ? MagentoHelper.buildUrl(domain, "carts/mine/items")
                : MagentoHelper.buildUrl(
                    domain, "guest-carts/$guestCartId/items"),
            body: convert.jsonEncode({"cartItem": params}),
            headers: token != null
                ? {
                    'Authorization': 'Bearer ' + token,
                    "content-type": "application/json"
                  }
                : {"content-type": "application/json"});
        final body = convert.jsonDecode(res.body);
        if (body["messages"] != null &&
            body["messages"]["error"] != null &&
            body["messages"]["error"][0].length > 0) {
          throw Exception(body["messages"]["error"][0]["message"]);
        } else if (body["message"] != null) {
          throw Exception(body["message"]);
        } else {
          print(body);
          return;
        }
      });
      return true;
    } catch (err) {
      rethrow;
    }
  }

  Future<bool> addItemsToCart(CartModel cartModel, String token) async {
    try {
      if (token != null) {
        //get cart info
        var res = await http.get(MagentoHelper.buildUrl(domain, "carts/mine"),
            headers: {'Authorization': 'Bearer ' + token});
        final cartInfo = convert.jsonDecode(res.body);
        if (res.statusCode == 200) {
          //amjad cart problem item_id
          return await addToCart(cartModel, token, cartInfo["id"],
              isDelete: true , cartItems:cartInfo["items"] );
        } else if (res.statusCode == 401) {
          throw Exception("Token expired. Please logout then login again");
        } else if (res.statusCode != 404) {
          throw Exception(MagentoHelper.getErrorMessage(cartInfo));
        }
      }

      //create a quote
      String url = token != null
          ? MagentoHelper.buildUrl(domain, "carts/mine")
          : MagentoHelper.buildUrl(domain, "guest-carts");
      var res = await http.post(url,
          headers: token != null ? {'Authorization': 'Bearer ' + token} : {});
      if (res.statusCode == 200) {
        if (token != null) {
          final quoteId = convert.jsonDecode(res.body);
          return await addToCart(cartModel, token, quoteId);
        } else {
          String quoteId = convert.jsonDecode(res.body);
          var response = await http
              .get(MagentoHelper.buildUrl(domain, "guest-carts/$quoteId"));
          final cartInfo = convert.jsonDecode(response.body);
          if (response.statusCode == 200) {
            final cartId = cartInfo["id"];
            guestQuoteId = quoteId;
            return await addToCart(cartModel, token, quoteId,
                guestCartId: cartId);
          } else {
            throw Exception(MagentoHelper.getErrorMessage(cartInfo));
          }
        }
      } else {
        throw Exception(
            MagentoHelper.getErrorMessage(convert.jsonDecode(res.body)));
      }
    } catch (err) {
      rethrow;
    }
  }
`

**Comment by amjadalfawal** [comment]
#issue1 : price not showing the fix in magento app/code/Mstore/ProductList/Model/ProductListRepository.php

in getList Function

```
    public function getList(\Magento\Framework\Api\SearchCriteriaInterface $searchCriteria)
    {
        /** @var \Magento\Catalog\Model\ResourceModel\Product\Collection $collection */
        $collection = $this->collectionFactory->create();
        $this->extensionAttributesJoinProcessor->process($collection);

        $collection->addAttributeToSelect('*');
        $collection->joinAttribute('status', 'catalog_product/status', 'entity_id', null, 'inner');
        $collection->joinAttribute('visibility', 'catalog_product/visibility', 'entity_id', null, 'inner');
	$collection->addMinimalPrice(); //adding minmalprice you can change to addFinalPrice amjad fluxstore


        $this->collectionProcessor->process($searchCriteria, $collection);

        $collection->load();

        $collection->addCategoryIds();
        $this->addExtensionAttributes($collection);
        $searchResult = $this->searchResultsFactory->create();
        $searchResult->setSearchCriteria($searchCriteria);
        $searchResult->setItems($collection->getItems());
        $searchResult->setTotalCount($collection->getSize());

        foreach ($collection->getItems() as $product) {
            $this->cacheProduct(
                $this->getCacheKey(
                    [
                        false,
                        $product->getStoreId()
                    ]
                ),
                $product
            );
        }

        return $searchResult;
    }


```

**Comment by amjadalfawal** [comment]
issue6: when social login in Magento order history  not retrived

**Comment by kevinsh25** [comment]
@amjadalfawal I am using Magento 2.3 on a good hosting and optimized site. Still facing issues in product loading in app. You got any solution for that?

**Comment by amjadalfawal** [comment]
@kevinsh25  the products are loading but there is like 3-second delay its take time  I didn't investigate this issue I use the same version 2.3

**Comment by amjadalfawal** [comment]
@kevinsh25  the response from the server takes about 1 second 
![image](https://user-images.githubusercontent.com/37481122/85231330-cc5e0400-b3fe-11ea-8182-767c8cc2dee5.png)

**Comment by amjadalfawal** [comment]
I implement the review feature in Magento 
![image](https://user-images.githubusercontent.com/37481122/85233307-fc60d380-b40d-11ea-92d2-974f39c88896.png)
#solved

**Comment by minhtruong315** [comment]
> @kevinsh25 the response from the server takes about 2.7 second and the app take about 10 seconds to reload the data when I find the problem or if I made any improvement I will share it here
> ![image](https://user-images.githubusercontent.com/37481122/85231400-47bfb580-b3ff-11ea-83c5-a9a0ce234773.png)

Thanks so much

**Comment by minhtruong315** [comment]
> issue 1: price not showing from outside.
> Magento API doesn't support to response price for configurable products. So it will show zero price for configurable products. We will investigate and upgrade it in the future.
> **I fixed this issue by editing the API**

Hi @amjadalfawal can u show me that you fixed for this issue?
Thanks

**Comment by amjadalfawal** [comment]
I show all the fixes on comment on the top I will mention you

**Comment by kevinsh25** [comment]
@minhtruong315 the speed and performance issue is common for everyone using Magento 2. You haven't found any solution for it and straight away closing tickets.

**Comment by amjadalfawal** [comment]
@kevinsh25 I just fixed a lot of issues in Magento I am fixing the caching issue for the users right now and then I will walk through the performance issue

**Comment by minhtruong315** [comment]
@amjadalfawal great thanks

**Comment by minhcasi** [comment]
@amjadalfawal - please also help us to create the Merge Request on gitlab if you would like to share the solution - we will help to merge the code and include the fix on next release - thank you so much for your time

**Comment by kevinsh25** [comment]
@amjadalfawal Have you found a fix for performance and speed issue?
Or can you share for caching?

**Comment by amjadalfawal** [comment]
> @amjadalfawal - please also help us to create the Merge Request on gitlab if you would like to share the solution - we will help to merge the code and include the fix on next release - thank you so much for your time

yes sure i can share my fixes soon 
@kevinsh25  first of all the caching in the app not working at all  you can try login and then close the app and open it you will find that you have to login in again so i changed the caching method to shared preference instead of local db

**Comment by kevinsh25** [comment]
@amjadalfawal did you get the time to share cache issue and performance issue?
