### ISSUE TITLE
M store pro any payment method does not work

### ISSUE THREAD

**Issue by ArifAnwar07** [inspireui/support#3802]
hello sir i have purchase m store  here is the proof
![IMG_20200618_193633](https://user-images.githubusercontent.com/67143715/85113154-763d6500-b234-11ea-9ea0-b7e96367aa6a.jpg)
sir when i m goint to checkout any pement method is not working here is issue screen shots
![Screenshot_20200618_193723](https://user-images.githubusercontent.com/67143715/85113273-a4bb4000-b234-11ea-9e4e-0952f15ac17c.jpg)
![Screenshot_20200618_193740](https://user-images.githubusercontent.com/67143715/85113281-a71d9a00-b234-11ea-93b7-8d2db2454a84.jpg)

and here is config file
[appconfig.zip](https://github.com/inspireui/support/files/4803425/appconfig.zip)

i have already uploud private files
in http://verify.inspireui.com 
 
sir please help me to fix the issue 
reply me as soon as possible..

**Comment by luyx2412** [comment]
HI @ArifAnwar07 Please follow the document https://docs.inspireui.com/mstore/getting-started/ to install the plugin. If still the issues, please invite inspireui.team@gmail.com to your dashboard wordpress. Let me investigate about it.

Thanks

**Comment by ArifAnwar07** [comment]
Sir have already update plugin Mstore Api plugin version is2.5.9 so i have emailed my website admin email and pass please check it.

**Comment by luyx2412** [comment]
Hi @ArifAnwar07 I just added mstore checkout page to your dashboard wordpress which will fix your checkout issue, so please check checkout feature in your app again.

Thanks

**Comment by ArifAnwar07** [comment]
@l uyx2412  sir i have chack my app  same error i m going delete my website and rebuild website  what error will fix or not?

**Comment by ArifAnwar07** [comment]
Hi @luyx2412  sir i have deleted my website  and rebuild  my website  but cod payment  method is not working i think the issue in m store source  code please fix this issue... please help me sir as soon as possible.

**Comment by luyx2412** [comment]
Hi @ArifAnwar07 can you give me the specific screenshot issue? If your cod payment did not work, please go to the Woocommerce payment setting and enable it.

Thanks

**Comment by ArifAnwar07** [comment]
@luyx2412  sir this issue screenshot
![Screenshot_20200618_193723](https://user-images.githubusercontent.com/67143715/85219623-3b1d6c00-b3c3-11ea-97c3-7ca3027339bd.jpg)
 
and I have already enable cod in my website.

![IMG_20200621_132511](https://user-images.githubusercontent.com/67143715/85219610-145f3580-b3c3-11ea-840a-d648a01dd268.jpg)

**Comment by luyx2412** [comment]
Hi @ArifAnwar07 Please send me your AppConfig again via inspireui.team@gmail.com. Because you changed it when re-install the website again. 

Thanks

**Comment by ArifAnwar07** [comment]
@luyx2412  hello sir i have mailed AppConfig file. So please check it and solve to issue thank you..

**Comment by ArifAnwar07** [comment]
@luyx2412  whatheppen sir Issue is fixed Or Not??

**Comment by minhcasi** [comment]
please move to the conversation to your latest issue #3862

**Comment by Osamasomy** [comment]
Hello sir i have same issue stripe payment method not display and then I press on it it redirect me on 404 page.
after some googling i will create a new page in wordpress name check-out but it still not working perfectly.

**Comment by ArifAnwar07** [comment]
> Hello sir i have same issue stripe payment method not display and then I press on it it redirect me on 404 page.
> after some googling i will create a new page in wordpress name check-out but it still not working perfectly.

Bro  please creat MStore checkout page and add template mstore api

**Comment by mvin10** [comment]
Hi , i have same issue, i have created MStore checkout page with mstore api template and still not works? any tips or somebody can help me here please :(  thank you

<img width="1212" alt="Captura de Pantalla 2020-07-19 a la(s) 20 49 49" src="https://user-images.githubusercontent.com/8391284/87895002-901fc280-ca01-11ea-8fbe-a5f5b27cab63.png">

**Comment by ArifAnwar07** [comment]
> Hi , i have same issue, i have created MStore checkout page with mstore api template and still not works? any tips or somebody can help me here please :(  thank you
> 
> <img width="1212" alt="Captura de Pantalla 2020-07-19 a la(s) 20 49 49" src="https://user-images.githubusercontent.com/8391284/87895002-901fc280-ca01-11ea-8fbe-a5f5b27cab63.png">
> 

Bro i have same issue  but nkt solved..
