### ISSUE TITLE
FluxStore Listing - Image loading Issue

### ISSUE THREAD

**Issue by mrizwanmmc** [inspireui/support#3891]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: Listing Image not showing.
+ Product & version: Fluxstore Listing 1.4.2
+ Flutter (or React Native) version: Flutter
+ Testing Device/Simulator:  Device
+ Screenshot issues (drag the file to attach here): ![issue](https://user-images.githubusercontent.com/10098991/85541359-5beaf900-b631-11ea-9425-bf9399733ae1.jpg)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com

_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by mrizwanmmc** [comment]
[See Video Issue](https://www.woclips.com/watch/URjcnBvOUok3Z2F)

**Comment by philipvu30** [comment]
Hi,

In your config.dart, please replace this line of code to this one 

![image](https://user-images.githubusercontent.com/54442328/85647666-2eea2500-b6c9-11ea-8fd0-a5cfbbf4787c.png)

**Comment by philipvu30** [comment]
Closed as no response in 2 days. 

If you are happy with our services/support, would you mind rating us on your [download page](https://codecanyon.net/downloads)?
We truly appreciate your help.

**Comment by mrizwanmmc** [comment]
Hi

I am facing two issues

1. Payment not work 
2. order history not showing

**Comment by philipvu30** [comment]
Hi,

I need a more detailed explanation of your issues than that. If possible, please provide images along with your issues. 

Thank you.

**Comment by mrizwanmmc** [comment]
1. When I book any server showing message Successful book but not redirect to the Payment page.

2. Order history Showing like below
[Order History](https://pindata.ams3.digitaloceanspaces.com/tutsfx/images/sb1.jpg)

I want to default listing like below, it's possible?
[Order History](https://pindata.ams3.digitaloceanspaces.com/tutsfx/images/sb2.jpg)

**Comment by mrizwanmmc** [comment]
One more Question plz.. 

How to to change preloader?

**Comment by minhcasi** [comment]
@mrizwanmmc - pls change it on this link - thank you!

<img width="1144" alt="Screen Shot 2020-07-06 at 11 06 38" src="https://user-images.githubusercontent.com/1459805/86554792-c4fb3680-bf78-11ea-8d10-161f08aef691.png">

**Comment by mrizwanmmc** [comment]
> 1. When I book any services showing message Successful book but not redirect to the Payment page.
> 2. Order history Showing like below
>    [Order History](https://pindata.ams3.digitaloceanspaces.com/tutsfx/images/sb1.jpg)
> 
> I want to default listing like below, it's possible?
> [Order History](https://pindata.ams3.digitaloceanspaces.com/tutsfx/images/sb2.jpg)


> 1. When I book any server showing message Successful book but not redirect to the Payment page.
> 2. Order history Showing like below
>    [Order History](https://pindata.ams3.digitaloceanspaces.com/tutsfx/images/sb1.jpg)
> 
> I want to default listing like below, it's possible?
> [Order History](https://pindata.ams3.digitaloceanspaces.com/tutsfx/images/sb2.jpg)

**Comment by mrizwanmmc** [comment]
Does anyone respond to me? Thank You :)

**Comment by philipvu30** [comment]
Hi,

We are working on the booking feature. It will be available in a few days as the current booking feature is outdated.

Thank you.

**Comment by philipvu30** [comment]
Hi,

The booking feature has been fixed. Please refer to this [answer](https://github.com/inspireui/support/issues/4087#issuecomment-658688685) to update your app.

Thank you.

**Comment by philipvu30** [comment]
Closed as no response in more than 2 days.

**Comment by mrizwanmmc** [comment]
Loading... loading... loadin...
[Please see attached error](https://pindata.ams3.digitaloceanspaces.com/upload/photos/2020/07/YR3lFfGKPoYhrrsywfF7_20_1c70e26ec5a0d6af2d9d898e05291a99_image.png)

**Comment by philipvu30** [comment]
Hi,

Please refer to this [answer](https://github.com/inspireui/support/issues/3743#issuecomment-659818921)

Thanks.

**Comment by mrizwanmmc** [comment]
[Please see this erry](https://pindata.ams3.digitaloceanspaces.com/upload/photos/2020/07/om5y9ETKhq4sma5JnMGA_22_d1042be798bc8fae709a32f8631197f8_image.jpg)
not solved please check error

**Comment by philipvu30** [comment]
Hi,

Please check this [solution](https://github.com/inspireui/support/issues/3743#issuecomment-662222399)

**Comment by mrizwanmmc** [comment]
I do everything in "Please check this [solution](https://github.com/inspireui/support/issues/3743#issuecomment-662222399)" 
but still, showing loading. 

and after booking not showing payment option also.

I send a web admin password and app code. 

Thank you :)
