### ISSUE TITLE
Onboarding Screen Repeating, Internet Connection prompt and Locate address interfering with opencart state drop down 

### ISSUE THREAD

**Issue by shamar112** [inspireui/support#4107]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 

1. the onboarding screen keeps coming back after I reopen the app after some time like for 1 hour then pick up the phone, it's showing the onboarding screen again on both debug and release.

2. locate address with google GPS API address filler: Using the recent updated opencart mstore API to get country and states when using the google GPS to input address it removes the states' dropdown field and leaves it with an empty text box to type the state with keyboard, but this throws an error when you type the state in the field because opencart don't use string but number zone ids.
 Can the state data be removed from the google GPS so it does not carry it over to state drop down and interfere with the state drop downfield? But only input the street address, city and zipcode from the GPS data.

3. When there is no internet connection the app does not show the prompt saying "Please check your internet".
 I load my config_en.json remotely to change banners and styles, so I would want the app to say that if the user does not have internet connectivity. If I disconnect the internet the app only shows a blank screen.

+ Product & version: 1.7.5
+ Flutter (or React Native) version: Flutter Opencart
+ Testing Device/Simulator: Samsung Device
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
Did it with Ticket #3863 

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by shamar112** [comment]
Got an email to submit form at http://verify.inspireui.com again, so I resent it. My previous ticket is https://github.com/inspireui/support/issues/3863 which I linked above

**Comment by minhtruong315** [comment]
Hi @shamar112 I messaged you on the skype. pls check
Thanks

**Comment by minhtruong315** [comment]
@shamar112 for issue 2, I will remove search address on google for opencart. You only can choose country and state when input address

**Comment by minhcasi** [comment]
Pls download the latest `1.7.6` for this fixing - let us know if you have any issue - thank you!

**Comment by shamar112** [comment]
I updated and tested issues 1 and 2 are resolved but for 3 the internet prompt issue, when I now disable internet the popup only shows for 2 seconds then disappears and moves on to the next screen not allowing the user whether to select open settings button.

here is a screen record of what am talking about. https://streamable.com/lv0bsx

**Comment by shamar112** [comment]
Also I was about to upload the app and realize another issue, the search screen is always loading even if nothing is typed in there, its the first I have seen it since I updated today.

here is the screen record link: https://streamable.com/kb05qh

**Comment by minhcasi** [comment]
@minhtruong315 - pls help to investigate this issue - thank you!

**Comment by shamar112** [comment]
Any updates on the search issue loading

**Comment by Maksish** [comment]
same issue

**Comment by minhcasi** [comment]
@shamar112 - sorry for late response on this ticket, we have updated the latest release `1.7.6` to upgrade the searching UX and performance, would you mind to have a check on your website config to see if is working smoothly?

**Comment by shamar112** [comment]
I already upgraded to 1.7.6 having the issue, do you mean the code has been updated again but have the same version 1.7.6. I first tried it with demo opencart

/// Server config demo for opencart
const serverConfig = {
  "type": "opencart",
  "url": "http://opencart-demo.mstore.io",
  "blog": "http://listeo.inspireui.com",
  "forgetPassword":
  "http://opencart-demo.mstore.io/index.php?route=account/forgotten"
};

**Comment by minhtruong315** [comment]
Hi @shamar112 I messaged you on the skype. pls check
Thanks

**Comment by minhcasi** [comment]
@shamar112 - please try with latest release `1.7.7` - we have fixed the no-internet issue and also upgrade some bug fix

**Comment by shamar112** [comment]
@minhcasi did a fresh install to test things out but getting errors
lib/app_init.dart:71:19: Error: 'CartModel' isn't a type.
Running Gradle task 'assembleDebug'...
      Provider.of<CartModel>(context, listen: false).changeCurrencyRates(
Running Gradle task 'assembleDebug'...
                  ^^^^^^^^^
Running Gradle task 'assembleDebug'...

I upgrade flutter and clear all cache

**Comment by shamar112** [comment]
updated to 1.7.7b the cartmodel error is gone but getting other issues

am testing out the no internet feature but when i disable wifi and open the app another error
![Screenshot_20200815-105840](https://user-images.githubusercontent.com/44536258/90316386-dc223200-deef-11ea-9aa4-68a08fa3d7ef.png)

also, the cart still not calculating properly

**Comment by minhcasi** [comment]
@shamar112 - could you help to share the cart screenshot issue - thanks

**Comment by shamar112** [comment]
@minhcasi here is the screen record video https://streamable.com/7zsia9

so the issue is the cart is doubling the cost each time a product option is changed even if the product is removed from the cart.

Step to reproduce
Tablet Product cost: 13,200
with product options: 32Gb $0.00 and 64Gb + $4,200

- Customer select 64Gb option
  **Cart total is: $17,400 which is correct**

- Customer does not want the 64Gb option again, so the customer removes it from the cart
  goes back to the product page and selects the 32Gb which does not have an additional cost
  **Cart Total: $17,400 which is incorrect the total should be showing $13,200 has the original cost**

- Customer now removes the item again from the cart and choose the 64GB
  **Cart Total: $34,000 which is incorrect again doubling the total**

The customer only chose 1 product quantity and removes the item from the cart when he/she wants to change and option but the cart keeps doubling the total unless the customer goes back to the home page and search for the product again and add it.

**Comment by minhcasi** [comment]
@shamar112 - thank you for the video, we will investigate and let you know

@minhtruong315

**Comment by kibbyboi** [comment]
![Screenshot_2020-08-19-09-05-38-741_com inspireui fluxstore](https://user-images.githubusercontent.com/4435840/90604365-054b0700-e1fd-11ea-8b28-6849fe75c10f.jpg)
I have this issue too , I can't Check out

**Comment by minhtruong315** [comment]
@kibbyboi you can change this config this common/config/products.dart
```
const kCartDetail = {
  "minAllowTotalCartValue": 100,
  "maxAllowQuantity": 10,
};
```

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
