### ISSUE TITLE
Issue on recent view product check out and wrong password error message

### ISSUE THREAD

**Issue by RatnApp** [inspireui/support#4712]
Hi Team,

First of all **thanks for this great product, we are live now**, using fluxstore as a our mobile application, **which works great for our scenario.**

We are facing few following issues in production, could you please help immediately:

1. If user goes to product from "Recent View" and adds the product to cart, we are getting an error , when user clicks on "check out" button, as a immediate remediation, our team is planning to switch off recent view, could you please let us know if this could be fixed and code be shared immediately so that we can incorporate the fixes in next update. Attached the screenshot of this issue. PS: we are using **webcheckout**, which redirects the app to website for checkout and **I will share the production android app link in form submission, you would be able to signup and reproduce the issue.**

![checkout issue](https://user-images.githubusercontent.com/69118014/90975322-b06fff00-e522-11ea-9b1c-70b0547dc3ad.PNG)

2. During sign in, if user authentication fails or user email id has spaces in it, user gets a wierd message than informing user that his/her email id or password is wrong. Attached the screenshot of this wierd error aswell.

![password wrong error message issue](https://user-images.githubusercontent.com/69118014/90975323-b06fff00-e522-11ea-9047-63e90664527a.PNG)

3. Sometimes, the change in variant by user doesn't change the price of the product.

4. When user adds product with discount price in cart, app sometimes shows the price before discount and sometime shows price after discount.

**All above issues could be reproduced by signing up to production app available in google play, I will send the link in the issue form. **

**Please note:** We had recently pulled the commit # c9f2e5fd84eaad2be39fb39860897b96bf6151a0 to resolve some of teh layout issues we were facing, before go live.

We would much appreciate your quick response on the first and second issue, we can wait on 3rd and 4th if it needs more time.

Also, for our information, is there any way we can access teh user log around issue 1 and 2 to understand how many production users are affected by this, please note we have not enabled firebase integration on the app.

**Thanks a lot.**

**Comment by RatnApp** [comment]
Hi Team, 

Found one more issue, if customer completes one order and doesn't close the app and captures few more items (from the menu option->BY CATAGORY-> pick any category->click on "see all"-. pick products and try to checkout, this produces the below issue, causing confusion for user on what could be the issue. From looks of it, it looks like needs initiating one more order session?

![image](https://user-images.githubusercontent.com/69118014/90983879-f3e95e00-e560-11ea-88b7-c73761bc0720.png)

Please let me know if I am working on unstable version of the branch, I can download the source code from stable version and release the app.

Thanks.

**Comment by minhcasi** [comment]
@RatnApp - congratulation to release the app on app stores - could you help to share the app URL so that we could give a test on these issues - thank you!

**Comment by RatnApp** [comment]
Hi @minhcasi - Thanks for the quick response, I have shared teh app link in google form submission, through which you would expect the license details. Please let me know if you need more details.

**Comment by RatnApp** [comment]
@minhcasi @luyx2412 _ Thinking of these issues, I do remember getting a proper message on password failed, however now it gives a technical error message, **do you think there could be any changes in the api or from shopify end**?

**Comment by RatnApp** [comment]
@minhcasi @luyx2412 - I am using **2020-07** shopify api version on the shopify server, while defining the private app (in webhook API version) could that be the reason for this behaviour, could you recommend which version should be setup ?

**Comment by luyx2412** [comment]
Hi @RatnApp Thanks for your detail, can you send me your current project via inspireui.team@gmail.com. Let me investigate easier.

Thanks

**Comment by RatnApp** [comment]
Hi  luyx2412,

Could you please let me know could I just share the lib folder, as the
whole project is big, it might not be feasible to share the code over gmail?

Regards,
Veggokart.

**Comment by RatnApp** [comment]
Hi  luyx2412,

We have just shared a access to zip file which contains the lib folder of
our project, we have also shared teh application link with you, please let
us know if you need anymore details.

Thanks.

**Comment by RatnApp** [comment]
@luyx2412 - Would you be able to revert back on this issue today, hopefully lib folder will help in reproducing

Thanks.

**Comment by RatnApp** [comment]
@luyx2412 @minhcasi  - Coudl you please let us know any updates on this 

Thanks.

**Comment by minhcasi** [comment]
@RatnApp - We have fixed this bug on latest release 1.7.7 - please help to update and let us know if you have any issues, thank you!

**Comment by RatnApp** [comment]
@minhcasi  - Thais great news, thanks for the quick help, coudl you possibly let me know how do I get 1.7.7, and upgrade to this version without breaking our existing customization

**Comment by minhcasi** [comment]
Hi Sir, pls follow this guideline - https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6

**Comment by RatnApp** [comment]
Hi @minhcasi , I could check out the code and build new apk, I coudl test login error scenario with wrong email (with spaces in email address), this issue still occurs, I am still seeing the long technical error than user friendly error, coudl you please advise.

Thanks

**Comment by luyx2412** [comment]
Hi @RatnApp You meant the error when login wrong credential is not right? We are improving about it. You can improve it in `lib/services/shopify.dart` line 722 with `createAccessToken` function.
```
      final QueryResult result = await client.query(options);
      var error = result.data['customerAccessTokenCreate']['userErrors'];

      if (error != null) {
        printLog(error.toString());
        throw Exception(error[0]['message']);
      }
```

Thanks

**Comment by RatnApp** [comment]
Thanks @luyx2412 let me give it a try today and revert back.

**Comment by RatnApp** [comment]
Thanks @luyx2412 , I could incorporate the code, I now get following error message,in case of wrong user id or password, which is lot better, however it would have been good, if message said **"invalid user id or password"**, is it something I have to customise on Shopify side and is that even available?

**"Warning:Exception:unidentified customer"**

Also, now with this code in, app doesn't authenticate me **even with the right password**, I get below message:

**"Warning:RangeError (length):invalid value:Valid value range is empty:0"**

Below is the create function modification **I have done in 1.7.5 source code:**




**Modified function is** :

createAccessToken({username, password}) async {
    try {
      print('::::request createAccessToken');

      const int nRepositories = 50;
      final QueryOptions options = QueryOptions(
          documentNode: gql(ShopifyQuery.createCustomerToken),
          variables: <String, dynamic>{
            'nRepositories': nRepositories,
            'input': {"email": username, "password": password}
          });

      final QueryResult result = await client.query(options);
      
      /*coment:Custom code to handle failed login scenario's*/
      var error = result.data['customerAccessTokenCreate']['userErrors'];

      if (error != null) {
        print(error.toString()); //this api is different 
        throw Exception(error[0]['message']);
      }

      /*comment:Custom code to handle failed login scenario's*/
      print("result ${result.data}");

      if (result.hasException) {
        print(result.exception.toString());
        throw Exception(result.exception.toString());
      }
      var json =
          result.data['customerAccessTokenCreate']['customerAccessToken'];
      print("json['accessToken'] ${json['accessToken']}");

      return json['accessToken'];
    } catch (e) {
      print('::::createAccessToken shopify error');
      print(e.toString());
      rethrow;
    }
  }

**Comment by RatnApp** [comment]
@minhcasi - Thanks for the quick answer #4846, could you also let us know how app will behave in offline scenario i.e., user download the app-> doesn't have active internet to download the config_en.json file , will app fallback on the local copy of the file?

Thanks!

**Comment by RatnApp** [comment]
@minhcasi - I did a quick round of testing around what happens if config_en.json is downloaded in time for user to open the app, **app goes blank**, this could be common scenario, if user downloads the app and opens later when he reaches a place where signal is very poor.

Coudl you please let us know if there is any plan to write a fallback code to look for in app config_en.json instead of app going blank?

If you guide us where this code is located, we can write the code ourself.

Thanks.

**Comment by luyx2412** [comment]
Hi @RatnApp You can store your config_en.json to localstorage, if something was wrong with the internet. You get the localstorage to load config_en.json. But the api need the network to get api, so i dont suggest use offline. https://pub.dev/packages/localstorage This is a document about localstorage.

Thanks
